from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path
import subprocess
from unittest.mock import patch


LIB_DIR = Path(__file__).resolve().parents[1] / "raspi_pxe_docker_fleet" / "rootfs" / "usr" / "local" / "lib" / "ha-pxe"
if str(LIB_DIR) not in sys.path:
    sys.path.insert(0, str(LIB_DIR))

from ha_pxe.client.firstboot import ensure_kernel_dhcp_resolver, ensure_networkmanager_ready


class _FakeLogger:
    def __init__(self) -> None:
        self.messages: list[str] = []

    def info(self, message: str) -> None:
        self.messages.append(f"info:{message}")

    def warning(self, message: str) -> None:
        self.messages.append(f"warn:{message}")


class EnsureKernelDhcpResolverTests(unittest.TestCase):
    def test_ensure_kernel_dhcp_resolver_writes_resolv_conf_from_proc_net_pnp(self) -> None:
        logger = _FakeLogger()

        with tempfile.TemporaryDirectory() as tmpdir:
            root_dir = Path(tmpdir)
            resolv_path = root_dir / "etc" / "resolv.conf"
            resolv_path.parent.mkdir(parents=True)
            resolv_path.write_text("nameserver 8.8.8.8\n", encoding="utf-8")

            pnp_path = root_dir / "proc" / "net" / "pnp"
            pnp_path.parent.mkdir(parents=True)
            pnp_path.write_text(
                "#PROTO: DHCP\n"
                "domain home.nyanya.org\n"
                "nameserver 192.168.25.1\n"
                "nameserver 1.1.1.1\n",
                encoding="utf-8",
            )

            target = ensure_kernel_dhcp_resolver(logger, root=root_dir)

            self.assertEqual(target, "/etc/resolv.conf")
            self.assertFalse(resolv_path.is_symlink())
            self.assertEqual(
                resolv_path.read_text(encoding="utf-8"),
                "# Generated by HA-PXE from kernel DHCP boot data\n"
                "search home.nyanya.org\n"
                "nameserver 192.168.25.1\n"
                "nameserver 1.1.1.1\n",
            )

    def test_ensure_kernel_dhcp_resolver_raises_when_nameserver_is_missing(self) -> None:
        logger = _FakeLogger()

        with tempfile.TemporaryDirectory() as tmpdir:
            root_dir = Path(tmpdir)
            resolv_path = root_dir / "etc" / "resolv.conf"
            resolv_path.parent.mkdir(parents=True)
            resolv_path.write_text("nameserver 8.8.8.8\n", encoding="utf-8")
            pnp_path = root_dir / "proc" / "net" / "pnp"
            pnp_path.parent.mkdir(parents=True)
            pnp_path.write_text("domain home.nyanya.org\n", encoding="utf-8")

            with self.assertRaisesRegex(RuntimeError, "did not provide any nameserver entries"):
                ensure_kernel_dhcp_resolver(logger, root=root_dir)

            self.assertFalse(resolv_path.is_symlink())
            self.assertEqual(resolv_path.read_text(encoding="utf-8"), "nameserver 8.8.8.8\n")


class EnsureNetworkManagerReadyTests(unittest.TestCase):
    def test_ensure_networkmanager_ready_checks_service_state_then_resolver(self) -> None:
        logger = _FakeLogger()
        commands: list[list[str]] = []

        def fake_run(command: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
            commands.append(command)
            check = kwargs.get("check", True)
            del check
            return subprocess.CompletedProcess(command, 0, "", "")

        with (
            patch("ha_pxe.client.firstboot.run", side_effect=fake_run),
        ):
            result = ensure_networkmanager_ready(logger)

        self.assertEqual(
            commands,
            [
                ["systemctl", "is-active", "--quiet", "NetworkManager.service"],
            ],
        )
        self.assertIsNone(result)
