"""Non-interactive locale, timezone, and keyboard configuration."""

from __future__ import annotations

from pathlib import Path

from ..envfile import parse_env_file
from ..fs_utils import atomic_write, replace_symlink
from ..shell import command_exists, run
from .bootstrap import BootstrapConfig


def apply_locale_defaults(config: BootstrapConfig, logger: object) -> None:
    keyboard_defaults = parse_env_file(Path("/etc/default/keyboard"))
    console_defaults = parse_env_file(Path("/etc/default/console-setup"))
    locale_defaults = parse_env_file(Path("/etc/default/locale"))

    keyboard_model = keyboard_defaults.get("XKBMODEL", "pc105")
    keyboard_layout = keyboard_defaults.get("XKBLAYOUT", "gb")
    keyboard_variant = keyboard_defaults.get("XKBVARIANT", "")
    keyboard_options = keyboard_defaults.get("XKBOPTIONS", "")
    keyboard_backspace = keyboard_defaults.get("BACKSPACE", "guess")

    console_charmap = console_defaults.get("CHARMAP", "UTF-8")
    console_codeset = console_defaults.get("CODESET", "guess")
    console_fontface = console_defaults.get("FONTFACE", "Do not change the boot/kernel font")
    console_fontsize = console_defaults.get("FONTSIZE", "")
    console_active_consoles = console_defaults.get("ACTIVE_CONSOLES", "/dev/tty[1-6]")
    console_font = console_defaults.get("FONT", "")
    console_font_map = console_defaults.get("FONT_MAP", "")
    console_map = console_defaults.get("CONSOLE_MAP", "")
    console_videomode = console_defaults.get("VIDEOMODE", "")

    locale_value = locale_defaults.get("LANG", "en_GB.UTF-8")
    timezone_value = "Etc/UTC"
    timezone_path = Path("/etc/timezone")
    if timezone_path.exists():
        timezone_value = timezone_path.read_text(encoding="utf-8").strip() or timezone_value

    if config.default_keyboard_layout:
        keyboard_layout = config.default_keyboard_layout
    if config.default_locale:
        locale_value = config.default_locale
    if config.default_timezone:
        timezone_value = config.default_timezone

    timezone_area, timezone_zone = _split_timezone(timezone_value)
    locale_charset = locale_value.split(".", 1)[1].split("@", 1)[0] if "." in locale_value else "UTF-8"

    logger.info(f"Applying locale defaults: locale={locale_value} timezone={timezone_value} keyboard={keyboard_layout}")

    keyboard_text = "\n".join(
        (
            "# KEYBOARD CONFIGURATION FILE",
            "",
            "# Consult the keyboard(5) manual page.",
            "",
            f'XKBMODEL="{keyboard_model}"',
            f'XKBLAYOUT="{keyboard_layout}"',
            f'XKBVARIANT="{keyboard_variant}"',
            f'XKBOPTIONS="{keyboard_options}"',
            "",
            f'BACKSPACE="{keyboard_backspace}"',
            "",
        )
    )
    atomic_write(Path("/etc/default/keyboard"), keyboard_text)

    console_lines = [
        "# CONFIGURATION FILE FOR SETUPCON",
        "",
        "# Consult the console-setup(5) manual page.",
        "",
        f'ACTIVE_CONSOLES="{console_active_consoles}"',
        "",
        f'CHARMAP="{console_charmap}"',
        "",
        f'CODESET="{console_codeset}"',
        f'FONTFACE="{console_fontface}"',
        f'FONTSIZE="{console_fontsize}"',
        "",
        f'VIDEOMODE="{console_videomode}"',
    ]
    if console_font:
        console_lines.append(f'FONT="{console_font}"')
    if console_font_map:
        console_lines.append(f'FONT_MAP="{console_font_map}"')
    if console_map:
        console_lines.append(f'CONSOLE_MAP="{console_map}"')
    atomic_write(Path("/etc/default/console-setup"), "\n".join(console_lines) + "\n")
    atomic_write(Path("/etc/default/locale"), f"#  File generated by update-locale\nLANG={locale_value}\n")

    locale_gen_path = Path("/etc/locale.gen")
    if locale_gen_path.exists():
        updated = False
        output_lines: list[str] = []
        for line in locale_gen_path.read_text(encoding="utf-8").splitlines():
            candidate = line.lstrip("# ").strip()
            if candidate == f"{locale_value} {locale_charset}":
                output_lines.append(f"{locale_value} {locale_charset}")
                updated = True
            else:
                output_lines.append(line)
        if not updated:
            output_lines.append(f"{locale_value} {locale_charset}")
        atomic_write(locale_gen_path, "\n".join(output_lines) + "\n")

    if command_exists("locale-gen"):
        run(["locale-gen", "--keep-existing"], check=False)
        run(["locale-gen"], check=False)
    if command_exists("update-locale"):
        run(["update-locale", f"LANG={locale_value}"], check=False)

    atomic_write(timezone_path, f"{timezone_value}\n")
    zoneinfo = Path("/usr/share/zoneinfo") / timezone_value
    if zoneinfo.exists():
        replace_symlink(Path("/etc/localtime"), str(zoneinfo))

    if command_exists("debconf-set-selections"):
        selections = [
            "debconf debconf/frontend select Noninteractive",
            "debconf debconf/priority select critical",
            f"keyboard-configuration keyboard-configuration/modelcode string {keyboard_model}",
            f"keyboard-configuration keyboard-configuration/layoutcode string {keyboard_layout}",
            "keyboard-configuration keyboard-configuration/store_defaults_in_debconf_db boolean true",
            "keyboard-configuration keyboard-configuration/model seen true",
            "keyboard-configuration keyboard-configuration/layout seen true",
            "keyboard-configuration keyboard-configuration/other seen true",
            "keyboard-configuration keyboard-configuration/unsupported_layout seen true",
            "keyboard-configuration keyboard-configuration/unsupported_config_layout seen true",
            "keyboard-configuration keyboard-configuration/unsupported_options seen true",
            "keyboard-configuration keyboard-configuration/unsupported_config_options seen true",
            "keyboard-configuration keyboard-configuration/toggle seen true",
            "keyboard-configuration keyboard-configuration/switch seen true",
            "keyboard-configuration keyboard-configuration/altgr seen true",
            "keyboard-configuration keyboard-configuration/compose seen true",
            "keyboard-configuration keyboard-configuration/ctrl_alt_bksp seen true",
            f"console-setup console-setup/charmap47 select {console_charmap}",
            f"console-setup console-setup/codesetcode string {console_codeset}",
            f"console-setup console-setup/fontface47 select {console_fontface}",
            "console-setup console-setup/store_defaults_in_debconf_db boolean true",
            "console-setup console-setup/charmap47 seen true",
            "console-setup console-setup/fontface47 seen true",
            "locales locales/default_environment_locale select {locale_value}".format(locale_value=locale_value),
            "locales locales/default_environment_locale seen true",
            f"tzdata tzdata/Areas select {timezone_area}",
            f"tzdata tzdata/Zones/{timezone_area} select {timezone_zone}",
            "tzdata tzdata/Areas seen true",
            f"tzdata tzdata/Zones/{timezone_area} seen true",
        ]
        if keyboard_variant:
            selections.insert(4, f"keyboard-configuration keyboard-configuration/variantcode string {keyboard_variant}")
        if keyboard_options:
            selections.insert(5, f"keyboard-configuration keyboard-configuration/optionscode string {keyboard_options}")
        if console_fontsize:
            selections.append(f"console-setup console-setup/fontsize string {console_fontsize}")
            selections.append("console-setup console-setup/fontsize seen true")
        run(["debconf-set-selections"], input_text="\n".join(selections) + "\n", check=False)

    if command_exists("setupcon"):
        run(["setupcon", "--save-only"], check=False)
    logger.info("Locale defaults written successfully")


def _split_timezone(value: str) -> tuple[str, str]:
    if "/" in value:
        area, zone = value.split("/", 1)
        return area, zone
    return "Etc", "UTC"

