#!/bin/bash
set -Eeuo pipefail

source /etc/ha-pxe/bootstrap.env

MARKER_FILE="/var/lib/ha-pxe/firstboot.done"

ensure_group_memberships() {
  local group
  IFS=',' read -ra groups <<<"${PXE_EXTRA_GROUPS:-}"
  for group in "${groups[@]}"; do
    [[ -n "${group}" ]] || continue
    if getent group "${group}" >/dev/null 2>&1; then
      usermod -aG "${group}" "${PXE_USERNAME}" || true
    fi
  done
}

configure_ssh_keys() {
  if [[ ! -s /etc/ha-pxe/authorized_keys ]]; then
    return 0
  fi

  install -d -m 700 -o "${PXE_USERNAME}" -g "${PXE_USERNAME}" "/home/${PXE_USERNAME}/.ssh"
  install -m 600 -o "${PXE_USERNAME}" -g "${PXE_USERNAME}" /etc/ha-pxe/authorized_keys "/home/${PXE_USERNAME}/.ssh/authorized_keys"
}

clear_stock_ssh_banner() {
  if command -v cancel-rename >/dev/null 2>&1; then
    cancel-rename "${PXE_USERNAME}" >/dev/null 2>&1 || true
  fi

  rm -f /etc/ssh/sshd_config.d/rename_user.conf
  if [[ -f /usr/share/userconf-pi/sshd_banner ]]; then
    : > /usr/share/userconf-pi/sshd_banner
  fi
}

seed_noninteractive_defaults() {
  local keyboard_model="pc105"
  local keyboard_layout="gb"
  local keyboard_variant=""
  local keyboard_options=""
  local keyboard_backspace="guess"
  local console_charmap="UTF-8"
  local console_codeset="guess"
  local console_fontface="Do not change the boot/kernel font"
  local console_fontsize=""
  local console_active_consoles="/dev/tty[1-6]"
  local console_font=""
  local console_font_map=""
  local console_map=""
  local console_videomode=""
  local locale_value="en_GB.UTF-8"
  local timezone_value="Etc/UTC"
  local timezone_area="Etc"
  local timezone_zone="UTC"
  local locale_charset="UTF-8"
  local XKBMODEL="" XKBLAYOUT="" XKBVARIANT="" XKBOPTIONS=""
  local BACKSPACE="" CHARMAP="" CODESET="" FONTFACE="" FONTSIZE="" ACTIVE_CONSOLES="" FONT="" FONT_MAP="" CONSOLE_MAP="" VIDEOMODE=""
  local LANG=""
  local locale_gen_tmp=""

  if [[ -f /etc/default/keyboard ]]; then
    # shellcheck disable=SC1091
    source /etc/default/keyboard
    keyboard_model="${XKBMODEL:-$keyboard_model}"
    keyboard_layout="${XKBLAYOUT:-$keyboard_layout}"
    keyboard_variant="${XKBVARIANT:-$keyboard_variant}"
    keyboard_options="${XKBOPTIONS:-$keyboard_options}"
    keyboard_backspace="${BACKSPACE:-$keyboard_backspace}"
  fi

  if [[ -f /etc/default/console-setup ]]; then
    # shellcheck disable=SC1091
    source /etc/default/console-setup
    console_charmap="${CHARMAP:-$console_charmap}"
    console_codeset="${CODESET:-$console_codeset}"
    if [[ -n "${FONTFACE:-}" ]]; then
      console_fontface="${FONTFACE}"
    fi
    console_fontsize="${FONTSIZE:-$console_fontsize}"
    console_active_consoles="${ACTIVE_CONSOLES:-$console_active_consoles}"
    console_font="${FONT:-$console_font}"
    console_font_map="${FONT_MAP:-$console_font_map}"
    console_map="${CONSOLE_MAP:-$console_map}"
    console_videomode="${VIDEOMODE:-$console_videomode}"
  fi

  if [[ -f /etc/default/locale ]]; then
    # shellcheck disable=SC1091
    source /etc/default/locale
    locale_value="${LANG:-$locale_value}"
  fi

  if [[ -f /etc/timezone ]]; then
    timezone_value="$(tr -d '\r\n' < /etc/timezone)"
  fi

  if [[ "${timezone_value}" == */* ]]; then
    timezone_area="${timezone_value%%/*}"
    timezone_zone="${timezone_value#*/}"
  fi

  if [[ -n "${PXE_DEFAULT_KEYBOARD_LAYOUT:-}" ]]; then
    keyboard_layout="${PXE_DEFAULT_KEYBOARD_LAYOUT}"
  fi

  if [[ -n "${PXE_DEFAULT_LOCALE:-}" ]]; then
    locale_value="${PXE_DEFAULT_LOCALE}"
  fi

  if [[ -n "${PXE_DEFAULT_TIMEZONE:-}" ]]; then
    timezone_value="${PXE_DEFAULT_TIMEZONE}"
    if [[ "${timezone_value}" == */* ]]; then
      timezone_area="${timezone_value%%/*}"
      timezone_zone="${timezone_value#*/}"
    fi
  fi

  if [[ "${locale_value}" == *.* ]]; then
    locale_charset="${locale_value#*.}"
    locale_charset="${locale_charset%%@*}"
  fi

  cat > /etc/default/keyboard <<EOF
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="${keyboard_model}"
XKBLAYOUT="${keyboard_layout}"
XKBVARIANT="${keyboard_variant}"
XKBOPTIONS="${keyboard_options}"

BACKSPACE="${keyboard_backspace}"
EOF

  cat > /etc/default/console-setup <<EOF
# CONFIGURATION FILE FOR SETUPCON

# Consult the console-setup(5) manual page.

ACTIVE_CONSOLES="${console_active_consoles}"

CHARMAP="${console_charmap}"

CODESET="${console_codeset}"
FONTFACE="${console_fontface}"
FONTSIZE="${console_fontsize}"

VIDEOMODE="${console_videomode}"
EOF

  if [[ -n "${console_font}" ]]; then
    printf 'FONT="%s"\n' "${console_font}" >> /etc/default/console-setup
  fi
  if [[ -n "${console_font_map}" ]]; then
    printf 'FONT_MAP="%s"\n' "${console_font_map}" >> /etc/default/console-setup
  fi
  if [[ -n "${console_map}" ]]; then
    printf 'CONSOLE_MAP="%s"\n' "${console_map}" >> /etc/default/console-setup
  fi

  printf '#  File generated by update-locale\nLANG=%s\n' "${locale_value}" > /etc/default/locale

  if [[ -f /etc/locale.gen ]]; then
    locale_gen_tmp="$(mktemp)"
    awk -v locale_name="${locale_value}" -v locale_charset="${locale_charset}" '
      BEGIN {
        updated = 0
      }
      {
        line = $0
        sub(/^[[:space:]]*#?[[:space:]]*/, "", line)
        gsub(/[[:space:]]+/, " ", line)
        if (line == locale_name " " locale_charset) {
          print locale_name " " locale_charset
          updated = 1
          next
        }
        print
      }
      END {
        if (!updated) {
          print locale_name " " locale_charset
        }
      }
    ' /etc/locale.gen > "${locale_gen_tmp}"
    mv "${locale_gen_tmp}" /etc/locale.gen
  fi

  if command -v locale-gen >/dev/null 2>&1; then
    locale-gen --keep-existing >/dev/null 2>&1 || locale-gen >/dev/null 2>&1 || true
  fi

  if command -v update-locale >/dev/null 2>&1; then
    update-locale LANG="${locale_value}" >/dev/null 2>&1 || true
  fi

  printf '%s\n' "${timezone_value}" > /etc/timezone
  if [[ -e "/usr/share/zoneinfo/${timezone_value}" ]]; then
    ln -snf "/usr/share/zoneinfo/${timezone_value}" /etc/localtime
  fi

  if command -v debconf-set-selections >/dev/null 2>&1; then
    {
      printf '%s\n' "debconf debconf/frontend select Noninteractive"
      printf '%s\n' "debconf debconf/priority select critical"
      printf '%s\n' "keyboard-configuration keyboard-configuration/modelcode string ${keyboard_model}"
      printf '%s\n' "keyboard-configuration keyboard-configuration/layoutcode string ${keyboard_layout}"
      if [[ -n "${keyboard_variant}" ]]; then
        printf '%s\n' "keyboard-configuration keyboard-configuration/variantcode string ${keyboard_variant}"
      fi
      if [[ -n "${keyboard_options}" ]]; then
        printf '%s\n' "keyboard-configuration keyboard-configuration/optionscode string ${keyboard_options}"
      fi
      printf '%s\n' "keyboard-configuration keyboard-configuration/store_defaults_in_debconf_db boolean true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/model seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/layout seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/variant seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/other seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/unsupported_layout seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/unsupported_config_layout seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/unsupported_options seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/unsupported_config_options seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/toggle seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/switch seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/altgr seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/compose seen true"
      printf '%s\n' "keyboard-configuration keyboard-configuration/ctrl_alt_bksp seen true"
      printf '%s\n' "console-setup console-setup/charmap47 select ${console_charmap}"
      printf '%s\n' "console-setup console-setup/codesetcode string ${console_codeset}"
      printf '%s\n' "console-setup console-setup/fontface47 select ${console_fontface}"
      if [[ -n "${console_fontsize}" ]]; then
        printf '%s\n' "console-setup console-setup/fontsize string ${console_fontsize}"
      fi
      printf '%s\n' "console-setup console-setup/store_defaults_in_debconf_db boolean true"
      printf '%s\n' "console-setup console-setup/charmap47 seen true"
      printf '%s\n' "console-setup console-setup/fontface47 seen true"
      printf '%s\n' "console-setup console-setup/fontsize seen true"
      printf '%s\n' "locales locales/default_environment_locale select ${locale_value}"
      printf '%s\n' "locales locales/default_environment_locale seen true"
      printf '%s\n' "tzdata tzdata/Areas select ${timezone_area}"
      printf '%s\n' "tzdata tzdata/Zones/${timezone_area} select ${timezone_zone}"
      printf '%s\n' "tzdata tzdata/Areas seen true"
      printf '%s\n' "tzdata tzdata/Zones/${timezone_area} seen true"
    } | debconf-set-selections
  fi

  if command -v setupcon >/dev/null 2>&1; then
    setupcon --save-only >/dev/null 2>&1 || true
  fi
}

main() {
  mkdir -p /var/lib/ha-pxe

  if [[ -f "${MARKER_FILE}" ]]; then
    exit 0
  fi

  hostnamectl set-hostname "${PXE_HOSTNAME}" || true

  if [[ ! -f /etc/hostname || "$(cat /etc/hostname)" != "${PXE_HOSTNAME}" ]]; then
    printf '%s\n' "${PXE_HOSTNAME}" > /etc/hostname
  fi

  if [[ -f /etc/hosts ]]; then
    if grep -q '^127\.0\.1\.1[[:space:]]' /etc/hosts; then
      sed -i -E "s/^127\.0\.1\.1[[:space:]].*/127.0.1.1\t${PXE_HOSTNAME}/" /etc/hosts
    else
      printf '127.0.1.1\t%s\n' "${PXE_HOSTNAME}" >> /etc/hosts
    fi
  fi

  if ! id "${PXE_USERNAME}" >/dev/null 2>&1; then
    useradd -m -s /bin/bash "${PXE_USERNAME}"
  fi

  if [[ -n "${PXE_PASSWORD_HASH:-}" ]]; then
    usermod -p "${PXE_PASSWORD_HASH}" "${PXE_USERNAME}"
  else
    passwd -l "${PXE_USERNAME}" || true
  fi

  seed_noninteractive_defaults

  export DEBIAN_FRONTEND=noninteractive
  export DEBCONF_FRONTEND=noninteractive
  export DEBCONF_NONINTERACTIVE_SEEN=true
  export DEBIAN_PRIORITY=critical
  export NEEDRESTART_MODE=a
  apt-get update
  apt-get install -y --no-install-recommends \
    -o Dpkg::Options::=--force-confdef \
    -o Dpkg::Options::=--force-confold \
    ca-certificates docker.io jq

  ensure_group_memberships
  configure_ssh_keys
  clear_stock_ssh_banner

  systemctl daemon-reload
  systemctl enable docker.service
  systemctl enable containerd.service || true
  systemctl enable ssh.service || true
  systemctl enable ha-pxe-container-sync.timer
  systemctl start docker.service
  systemctl start ssh.service || true
  systemctl try-reload-or-restart ssh.service || true
  systemctl start ha-pxe-container-sync.service || true
  systemctl start ha-pxe-container-sync.timer

  touch "${MARKER_FILE}"
}

main "$@"
